"""Change members column to store usernames

Revision ID: a90feb33316e
Revises: acc4a9200411
Create Date: 2024-05-18 23:12:19.477067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a90feb33316e'
down_revision = 'acc4a9200411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing', 'members',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing', 'members',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    # ### end Alembic commands ###
